// packages/vue/src/Klad.vue
<script setup lang="ts">
import {
  createKlad,
  type ChartState,
  type NodeContext,
  type Options,
  type KladApi,
  type KladEvents,
} from '@klad/core'
import { h, onBeforeUnmount, onMounted, provide, render, shallowRef, watch, type VNode } from 'vue'
import { ORG_CHART_KEY } from './useKlad.js'

const props = defineProps<{ options: Options }>()
const emit = defineEmits<{
  nodeClick: Parameters<KladEvents['nodeClick']>
  nodeHover: Parameters<KladEvents['nodeHover']>
  nodeDblClick: Parameters<KladEvents['nodeDblClick']>
  /**
   * A node was dropped somewhere new, BEFORE anything moves. Call the event's
   * own `preventDefault()` to refuse it — Vue's emit has no return channel,
   * so the veto travels on the payload rather than as a return value.
   */
  nodeDrop: Parameters<KladEvents['nodeDrop']>
  childrenLoaded: Parameters<KladEvents['childrenLoaded']>
  toggle: Parameters<KladEvents['toggle']>
  warning: Parameters<KladEvents['warning']>
  ready: Parameters<KladEvents['ready']>
}>()

const slots = defineSlots<{ node?: (context: NodeContext) => VNode[] }>()

const hostRef = shallowRef<HTMLElement | null>(null)
const api = shallowRef<KladApi | null>(null)
const state = shallowRef<ChartState | null>(null)

let chart: ReturnType<typeof createKlad> | null = null

/**
 * Slot content is rendered into each pooled overlay element with Vue's
 * `render()`. The vanilla layer reuses the same `HTMLElement` per visible
 * slot across frames (see packages/core/src/overlay.ts) rather than
 * recreating DOM, so calling `render()` again on that same element lets Vue
 * patch the previous tree instead of remounting it — that reuse is what
 * keeps panning smooth at high node counts. This set only tracks which
 * elements currently hold a mounted Vue tree, so it can be unmounted
 * cleanly (`render(null, element)`) when the chart is destroyed instead of
 * being ripped out of the DOM with its component instances still live.
 */
const overlayElements = new Set<HTMLElement>()

const WRAPPER_STYLE = { display: 'block', boxSizing: 'border-box', width: '100%', height: '100%' } as const

/** Options with `renderNode` attached only when there is slot content to render. */
function withRenderNode(options: Options): Options {
  return slots.node === undefined ? { ...options } : { ...options, renderNode }
}

function renderNode(element: HTMLElement, context: NodeContext): void {
  const node = slots.node
  if (node === undefined) return
  // The wrapper fills the overlay slot it is rendered into. The slot element
  // already carries an inline width/height matching the declared nodeSize, but
  // this div sits between them, so without stretching it a percentage height on
  // the consumer's card has nothing to resolve against and the card collapses to
  // its content — leaving the canvas-drawn box visible underneath. Vanilla has no
  // such wrapper, so omitting this makes the two adapters disagree.
  render(
    h('div', { class: 'orgchart-node', style: WRAPPER_STYLE }, node(context)),
    element,
  )
  overlayElements.add(element)
}

onMounted(() => {
  if (hostRef.value === null) return
  // Only claim the overlay when a #node slot actually exists. Passing
  // `renderNode` unconditionally makes the vanilla layer allocate and position
  // an element per visible node to hand to a callback that returns immediately —
  // so a Vue consumer who wants the plain canvas chart would still pay for DOM
  // that a frameworkless consumer does not. Same tier, either way.
  chart = createKlad(hostRef.value, withRenderNode(props.options))
  api.value = chart.api
  chart.subscribe((next) => (state.value = next))
  chart.on('nodeClick', (event) => emit('nodeClick', event))
  chart.on('nodeHover', (event) => emit('nodeHover', event))
  chart.on('nodeDblClick', (event) => emit('nodeDblClick', event))
  // Emitted SYNCHRONOUSLY, which is what makes `preventDefault()` on the
  // payload work: the vanilla layer reads it back the instant this returns.
  chart.on('nodeDrop', (event) => emit('nodeDrop', event))
  chart.on('childrenLoaded', (event) => emit('childrenLoaded', event))
  chart.on('toggle', (event) => emit('toggle', event))
  chart.on('warning', (warning) => emit('warning', warning))
  chart.on('ready', () => emit('ready'))
})

watch(
  () => props.options,
  (next) => chart?.update(next.data, withRenderNode(next)),
  { deep: true },
)

onBeforeUnmount(() => {
  chart?.destroy()
  chart = null
  api.value = null
  for (const element of overlayElements) render(null, element)
  overlayElements.clear()
})

provide(ORG_CHART_KEY, { api, state })
defineExpose({ api })
</script>

<template>
  <div ref="hostRef" class="orgchart" />
</template>

// packages/react/src/Klad.tsx
import {
  createKlad,
  type ChartState,
  type NodeContext,
  type Options,
  type KladApi,
  type KladEvents,
  type KladInstance,
} from '@klad/core'
import {
  useCallback,
  useEffect,
  useImperativeHandle,
  useLayoutEffect,
  useReducer,
  useRef,
  useState,
  useSyncExternalStore,
  type CSSProperties,
  type ReactNode,
  type Ref,
} from 'react'
import { createPortal } from 'react-dom'
import { KladContext } from './useKlad.js'

export interface KladHandle {
  api: KladApi | null
}

export interface KladProps {
  options: Options
  /**
   * Render prop for node content — React's equivalent of the vanilla layer's
   * `renderNode(el, ctx)` callback and the Vue adapter's `#node` scoped slot.
   * Attached to the chart's `renderNode` option only when defined (see
   * `withRenderNode` below): a React consumer who wants the plain canvas
   * chart pays nothing for overlay DOM, exactly like the vanilla and Vue
   * paths.
   */
  children?: (context: NodeContext) => ReactNode
  className?: string
  style?: CSSProperties
  ref?: Ref<KladHandle>
  onNodeClick?: KladEvents['nodeClick']
  onNodeHover?: KladEvents['nodeHover']
  onNodeDblClick?: KladEvents['nodeDblClick']
  /** A node was dropped somewhere new, before anything moves. Call the event's
   * `preventDefault()` to refuse it. */
  onNodeDrop?: KladEvents['nodeDrop']
  onChildrenLoaded?: KladEvents['childrenLoaded']
  onToggle?: KladEvents['toggle']
  onWarning?: KladEvents['warning']
  onReady?: KladEvents['ready']
}

/**
 * One pooled overlay `<div>` from packages/vanilla/src/overlay.ts, and the
 * latest node context the vanilla layer handed it. `key` is assigned once,
 * the first time this particular element is seen, and never changes for the
 * element's lifetime. That is what keeps the portal below stable across
 * frames: the vanilla layer reuses the same `HTMLElement` per pooled slot
 * rather than recreating DOM as panning reassigns which chart node a slot
 * shows (see the overlay module for why), and keying the portal to the
 * element rather than to the node it currently displays is what lets React
 * patch the existing subtree instead of unmounting and remounting it every
 * frame the camera moves.
 */
interface Slot {
  key: number
  element: HTMLElement
  context: NodeContext
}

/**
 * The wrapper fills the overlay slot it is rendered into. The slot element
 * already carries an inline width/height matching the declared nodeSize, but
 * this div sits between them, so without stretching it a percentage height
 * on the consumer's card has nothing to resolve against and the card
 * collapses to its content — leaving the canvas-drawn box visible
 * underneath. Vanilla has no such wrapper, so omitting this would make this
 * adapter disagree with vanilla and Vue. Mirrors Klad.vue's
 * `WRAPPER_STYLE` exactly.
 */
const WRAPPER_STYLE: CSSProperties = { display: 'block', boxSizing: 'border-box', width: '100%', height: '100%' }

/**
 * Binds React to `@klad/core`. Every chart behaviour — layout, canvas
 * drawing, hit-testing, pointer/keyboard input, the worker — lives in the
 * vanilla layer; this component only creates it, keeps it in sync with
 * props, and renders node content through portals into the overlay elements
 * the vanilla layer hands back.
 */
export function Klad(props: KladProps): ReactNode {
  const { options, children, className, style, ref } = props

  const hostRef = useRef<HTMLDivElement | null>(null)
  const [instance, setInstance] = useState<KladInstance | null>(null)
  const [api, setApi] = useState<KladApi | null>(null)

  // Read by the stable `renderNode` callback below, so a new render-prop
  // function identity (an inline arrow function is a new identity on every
  // render, same as any React render prop) never has to recreate the chart —
  // only a genuine option change goes through `chart.update()`.
  const childrenRef = useRef(children)
  childrenRef.current = children
  const hasChildren = children !== undefined

  // Latest event handlers, read from inside the `chart.on(...)` subscriptions
  // set up once at creation — same reasoning as `childrenRef`.
  const handlersRef = useRef({
    onNodeClick: props.onNodeClick,
    onNodeHover: props.onNodeHover,
    onNodeDblClick: props.onNodeDblClick,
    onNodeDrop: props.onNodeDrop,
    onChildrenLoaded: props.onChildrenLoaded,
    onToggle: props.onToggle,
    onWarning: props.onWarning,
    onReady: props.onReady,
  })
  handlersRef.current = {
    onNodeClick: props.onNodeClick,
    onNodeHover: props.onNodeHover,
    onNodeDblClick: props.onNodeDblClick,
    onNodeDrop: props.onNodeDrop,
    onChildrenLoaded: props.onChildrenLoaded,
    onToggle: props.onToggle,
    onWarning: props.onWarning,
    onReady: props.onReady,
  }

  // --- overlay bookkeeping ---
  // One `Slot` per pooled element, never one per chart node. `renderNode`
  // fires from inside the vanilla layer's rAF loop, outside React's render
  // cycle entirely, so it can only stash the latest context on the existing
  // slot (or create one the first time this element is seen) and ask React
  // to re-render — it must never mint a fresh key for an element it has
  // already seen, or the portal keyed to that element would unmount and
  // remount every frame the camera moves, which is exactly the churn the
  // pool exists to avoid (see the identity test in
  // orgchart.browser.test.tsx).
  const slotsRef = useRef(new Map<HTMLElement, Slot>())
  const nextKeyRef = useRef(0)
  const [, forceRender] = useReducer((n: number) => n + 1, 0)

  const renderNode = useCallback((element: HTMLElement, context: NodeContext): void => {
    if (childrenRef.current === undefined) return
    const existing = slotsRef.current.get(element)
    if (existing === undefined) {
      slotsRef.current.set(element, { key: nextKeyRef.current++, element, context })
    } else {
      existing.context = context
    }
    forceRender()
  }, [])

  /**
   * Options with `renderNode` attached only when there is content to render.
   * Passing it unconditionally would make the vanilla layer allocate and
   * position an overlay element per visible node for a callback that does
   * nothing — so a React consumer wanting the plain canvas chart would pay
   * for DOM a frameworkless consumer does not. Same tier either way.
   */
  const withRenderNode = useCallback(
    (base: Options): Options => (hasChildren ? { ...base, renderNode } : { ...base }),
    [hasChildren, renderNode],
  )

  // Whether the next `chart.update()` request (see the effect below) should
  // be skipped. It should be, exactly once, right after the chart is
  // created: that commit's `options`/`hasChildren` are exactly what the
  // chart was just constructed with, and `update()` additionally resets
  // every node's open/closed state via the vanilla layer's `initOpen()`,
  // which would silently undo real expand/collapse state if it ever ran
  // redundantly.
  const skipNextUpdateRef = useRef(true)

  useLayoutEffect(() => {
    const host = hostRef.current
    if (host === null) return

    skipNextUpdateRef.current = true
    const chart = createKlad(host, withRenderNode(options))
    setInstance(chart)
    setApi(chart.api)

    const unsubscribers = [
      chart.on('nodeClick', (event) => handlersRef.current.onNodeClick?.(event)),
      chart.on('nodeHover', (event) => handlersRef.current.onNodeHover?.(event)),
      chart.on('nodeDblClick', (event) => handlersRef.current.onNodeDblClick?.(event)),
      chart.on('nodeDrop', (event) => handlersRef.current.onNodeDrop?.(event)),
      chart.on('childrenLoaded', (event) => handlersRef.current.onChildrenLoaded?.(event)),
      chart.on('toggle', (event) => handlersRef.current.onToggle?.(event)),
      chart.on('warning', (warning) => handlersRef.current.onWarning?.(warning)),
      chart.on('ready', () => handlersRef.current.onReady?.()),
    ]

    return () => {
      for (const off of unsubscribers) off()
      chart.destroy()
      setInstance(null)
      setApi(null)
      // Dropping every slot — rather than leaving stale elements keyed to a
      // destroyed chart — is what lets the portals below unmount cleanly on
      // this same commit instead of leaking mounted trees under DOM that
      // `chart.destroy()` already detached.
      slotsRef.current.clear()
    }
    // Mount once: `options`/`hasChildren` changes are handled by the effect
    // below via `chart.update()`, never by recreating the chart.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  useEffect(() => {
    if (instance === null) return
    if (skipNextUpdateRef.current) {
      skipNextUpdateRef.current = false
      return
    }
    instance.update(options.data, withRenderNode(options))
  }, [instance, options, withRenderNode])

  // `useSyncExternalStore`, not `useState` updated from an effect:
  // `subscribe` is an external store the vanilla layer owns, and this is the
  // hook React provides with correct tearing behaviour under concurrent
  // rendering for exactly that shape. `cachedStateRef` holds the precise
  // object `subscribe`'s listener last received; `getSnapshot` returns that
  // same cached reference between notifications rather than recomputing one,
  // because a getSnapshot that returns a new object identity on every call
  // reads to React as a store that is changing on every render.
  const cachedStateRef = useRef<ChartState | null>(null)
  const subscribe = useCallback(
    (onStoreChange: () => void): (() => void) => {
      if (instance === null) return () => {}
      return instance.subscribe((next) => {
        cachedStateRef.current = next
        onStoreChange()
      })
    },
    [instance],
  )
  const getSnapshot = useCallback((): ChartState | null => cachedStateRef.current, [])
  const state = useSyncExternalStore(subscribe, getSnapshot, getSnapshot)

  useImperativeHandle(ref, () => ({ api }), [api])

  const slots = Array.from(slotsRef.current.values())
  // Fixed "orgchart" marker class plus whatever the consumer passed, mirroring
  // Klad.vue's template (`class="orgchart"` on its root, with Vue's
  // automatic fallthrough merging in the caller's own `class`).
  const hostClassName = className === undefined ? 'orgchart' : `orgchart ${className}`

  return (
    <KladContext.Provider value={{ api, state }}>
      <div ref={hostRef} className={hostClassName} style={style} />
      {hasChildren
        ? slots.map((slot) =>
            createPortal(
              <div className="orgchart-node" style={WRAPPER_STYLE}>
                {children(slot.context)}
              </div>,
              slot.element,
              String(slot.key),
            ),
          )
        : null}
    </KladContext.Provider>
  )
}
